# Generated by Django 5.1.1 on 2025-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_contact_fullname_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_earned', models.DateField()),
                ('certificate_link', models.URLField()),
            ],
        ),
    ]
