# Generated by Django 5.1.1 on 2025-11-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='company',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
