# Generated by Django 5.1.1 on 2025-11-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_link_project_github_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
